# Generated by Django 4.1.5 on 2023-01-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
