# Generated by Django 4.1.5 on 2023-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_complainttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitaltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(max_length=50)),
            ],
        ),
    ]
