# Generated by Django 4.1.5 on 2023-02-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
                ('doctor', models.IntegerField(default=0)),
                ('hospital', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.CharField(default='Not Yet Viewed', max_length=50)),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.complainttype')),
            ],
        ),
    ]
