# Generated by Django 4.1.5 on 2023-02-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=50)),
                ('user', models.IntegerField(default=0)),
                ('doctor', models.IntegerField(default=0)),
                ('hospital', models.IntegerField(default=0)),
            ],
        ),
    ]
