# Generated by Django 4.1.5 on 2023-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0003_slots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
