# Generated by Django 4.1.5 on 2023-01-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
