# Generated by Django 4.1.5 on 2023-01-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_place'),
        ('Guest', '0003_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='logo/')),
                ('proof', models.FileField(upload_to='proof/')),
                ('photo', models.FileField(upload_to='images/')),
                ('password', models.CharField(max_length=50, unique=True)),
                ('hospitaltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hospitaltype')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
