# Generated by Django 4.1.5 on 2023-01-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
