# Generated by Django 4.1.5 on 2023-01-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_hospital'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('headname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.hospital')),
            ],
        ),
    ]
