# Generated by Django 4.1.5 on 2023-02-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='images/')),
                ('medicine_details', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.appointment')),
            ],
        ),
    ]
