# Generated by Django 4.1.5 on 2023-02-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_medicinereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinereport',
            old_name='medicine_details',
            new_name='report_details',
        ),
    ]
